api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    eager_loading:
        enabled: true
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
            client_enabled: true
            enabled_parameter_name: pagination
            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            partial: false # set this option to true for better performance, but will not give back the last page or the total of items, only the next page
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exceptions\EmptyBodyException: 400
        App\Exceptions\InvalidConfirmationTokenException: 404